/*
 * A class that keeps track of word-frequecy data.
 * 
 * Further documentation is in SimpleWordFreqList.cpp
 * 
 * STUDENTS DO NOT EDIT THIS FILE.
 *
 * Mark A. Sheldon, Tufts Uiversity, Spring 2021
 */

/*******************************************************************
 *    CAUTION:                                                     *
 *    YOU MUST LEAVE THIS FILE UNCHANGED.                          *
 *                                                                 *
 *    Read it for your own amusement and education.                *
 *******************************************************************/
#ifndef SIMPLEWORDFREQLIST_H
#define SIMPLEWORDFREQLIST_H

#include <string>

#include "WordFreqLinkedList.h"

class WordFreqList
{
public:
        WordFreqList();
        ~WordFreqList();

        int      size();
        void     countOccurrence(std::string word);
        WordFreq get(int index);

        void     debugPrint();

private:
        WordFreqLinkedList wflist;
        
        friend class SimpleWordFreqTester;  // A friend class for testing

        /* 
         * Making copy constructor and assignment operator private
         * to prevent their inadvertant use from compiling.
         * Students do NOT implement these
         */
        WordFreqList(WordFreqList &other);
        WordFreqList &operator=(WordFreqList &rhs);
};

#endif
